use_frameworks!
platform :ios, '13.0'

target 'tms-social-lib_Example' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'tms-social-lib', :path => '../'

  pod 'FBSDKCoreKit', ' 11.2.1'
  pod 'FBSDKLoginKit', ' 11.2.1'
  pod 'LineSDKSwift', '5.7.0'
  pod 'GoogleSignIn', '6.0.1'
  pod 'OAuthSwift', '2.2.0'

  target 'tms-social-lib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    # pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    installer.pods_project.build_configurations.each do |config|
     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
 end
end
